version: '2'

services:

  redis:
    image: redis:alpine
    mem_reservation: 200M
    mem_limit: 256m
    cpus: 1.25
    ports:
      - "6379:6379"
  adservice:
    mem_limit: 300m
    mem_reservation: 180M 
    cpus: 0.2
    build:
      context: ./src/adservice
      dockerfile: Dockerfile 
    ports: 
      - "9555:9555"
    env_file:
      - ./src/adservice/env.list 
  cartservice:
    mem_limit: 128m
    mem_reservation: 64M
    cpus: 0.2
    build:
      context: ./src/cartservice/src
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    env_file:
      - ./src/cartservice/src/env.list
  checkoutservice:
    cpus: 0.1
    mem_limit: 128m
    mem_reservation: 64M
    build:
      context: ./src/checkoutservice
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    env_file:
      - ./src/checkoutservice/env.list
  currencyservice:
    mem_limit: 128m
    mem_reservation: 64M
    cpus: 0.1
    build:
      context: ./src/currencyservice
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    env_file:
      - ./src/currencyservice/env.list
  emailservice:
    mem_limit: 128m
    mem_reservation: 64M
    cpus: 0.1
    build:
      context: ./src/emailservice
      dockerfile: Dockerfile
    ports:
        - "8081:8081"
    env_file:
      - ./src/emailservice/env.list 
  frontend:
    mem_limit: 128m
    mem_reservation: 64M
    cpus: 0.1
    build: 
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    env_file:
      - ./src/frontend/env.list
  paymentservice:
    mem_limit: 128m
    mem_reservation: 64M
    cpus: 0.1
    build: 
      context: ./src/paymentservice
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    env_file:
      - ./src/paymentservice/env.list
  productcatalogservice:
    mem_limit: 128m
    mem_reservation: 64M
    cpus: 0.1
    build:
      context: ./src/productcatalogservice
      dockerfile: Dockerfile
    ports:
      - "3550:3550"
    env_file:
      - ./src/productcatalogservice/env.list
  recommendationservice:
    mem_limit: 300m
    mem_reservation: 220M
    cpus: 0.1
    build:
      context: ./src/recommendationservice
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - ./src/recommendationservice/env.list
  shippingservice:
    mem_limit: 128m
    mem_reservation: 64M
    cpus: 0.1
    build:
      context: ./src/shippingservice
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    env_file:
      - ./src/shippingservice/env.list
  loadgenerator:
    mem_limit: 521M 
    mem_reservation: 256m
    cpus: 0.3
    build:
      context: ./src/loadgenerator
      dockerfile: Dockerfile
    env_file:
      - ./src/loadgenerator/env.list
    volumes:
      - locust_files_10:/loadgen

volumes:
  locust_files_10:

 