version: '3.7'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '1.25'
          memory: 300M
        reservations:
          cpus: '1.25'
          memory: 180M

  adservice:
    image: drarazvan/adservice:latest
    build:
      context: ./src/adservice
      dockerfile: Dockerfile    
    ports: 
      - "9555:9555"
    env_file:
      - ./src/adservice/env.list 
    deploy:
      resources:
        limits:
          cpus: '0.5' 
          memory: 300M
        reservations:
          cpus: '0.2'
          memory: 180M
    
  cartservice:
    image: drarazvan/cartservice:latest
    build:
      context: ./src/cartservice/src
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    env_file:
      - ./src/cartservice/src/env.list
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 128M
        reservations:
          cpus: '0.2'
          memory: 64M
  checkoutservice:
    image: drarazvan/checkoutservice:latest
    build:
      context: ./src/checkoutservice
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    env_file:
      - ./src/checkoutservice/env.list
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
  currencyservice:
    image: drarazvan/currencyservice:latest
    build:
      context: ./src/currencyservice
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    env_file:
      - ./src/currencyservice/env.list 
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M

  emailservice:
    image: drarazvan/emailservice:latest
    build:
      context: ./src/emailservice
      dockerfile: Dockerfile
    ports:
        - "8081:8081"
    env_file:
      - ./src/emailservice/env.list 
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.2'
          memory: 64M

  frontend:
    image: drarazvan/frontend:latest
    build: 
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    env_file:
      - ./src/frontend/env.list
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          cpus: '0.3'
          memory: 64M
  paymentservice:
    image: drarazvan/paymentservice:latest
    build: 
      context: ./src/paymentservice
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    env_file:
      - ./src/paymentservice/env.list
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M

  productcatalogservice:
    image: drarazvan/productcatalogservice:latest
    build:
      context: ./src/productcatalogservice
      dockerfile: Dockerfile
    ports:
      - "3550:3550"
    env_file:
      - ./src/productcatalogservice/env.list
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
          
  recommendationservice:
    image: drarazvan/recommendationservice:latest
    build:
      context: ./src/recommendationservice
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - ./src/recommendationservice/env.list
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 300M
        reservations:
          cpus: '0.1'
          memory: 220M
  shippingservice:
    image: drarazvan/shippingservice:latest
    build:
      context: ./src/shippingservice
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    env_file:
      - ./src/shippingservice/env.list
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M

  loadgenerator:
    image: drarazvan/loadgenerator:latest
    build:
      context: ./src/loadgenerator
      dockerfile: Dockerfile
    env_file:
      - ./src/loadgenerator/env.list
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 512M
        reservations:
          cpus: '0.3'
          memory: 256M

    volumes:
      - locust_files_swarm_10:/loadgen

volumes:
  locust_files_swarm_10:
